### ISSUE TITLE
change our CI (org-wide) to use AdoptOpenJDK

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#587]
@adriaanm I wrote down "create an Adopt OpenJDK ticket, assign it to myself, say I plan to do it in January" but now I can't remember what this meant exactly... was it to add AdoptOpenJDK to our scala/scala CI matrix, or the community build, or what? if you can't remember either I can review the team meeting video and find out

**Comment by adriaanm** [comment]
it was originally about standardizing on adoptopenjdk hotspot on travis ci (installed using jabba), but in the mean time we're no longer sure because they have [not yet been able to license the TCK](https://adoptopenjdk.net/quality.html)

**Comment by SethTisue** [comment]
okay, we'll do nothing for now, and re-sync with others at Lightbend on this in January or whenever. it's mainly downstream projects (Akka, Play, etc) where it might really matter actually, so we can wait and follow their lead.

**Comment by SethTisue** [comment]
note to self, since I already forgot once: the issue is that Oracle OpenJDK, which we're currently using on our own machines and on Jenkins and Travis, will eventually stop receiving security updates. that's the reason we will ultimately want to be using AdoptOpenJDK (or something)

**Comment by dwijnand** [comment]
Setting up Travis CI to use AdoptOpenJDK is quite simple:

```yaml
before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install adopt@1.8.202-08 && jabba use "$_" && java -version
```

An example of a matrix using v8 and v11, with v11 being allowed to fail:

```yaml
before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use "$_" && java -version

env:
  - TRAVIS_JDK=adopt@1.8.202-08
  - TRAVIS_JDK=adopt@1.11.0-2

matrix:
  fast_finish: true
  allow_failures:
    - env: TRAVIS_JDK=adopt@1.11.0-2 # not fully supported but allows problem discovery
```

And don't forget to cache the installed jdks:

```yaml
cache:
  directories:
    - $HOME/.jabba/jdk
```
