### ISSUE TITLE
Travis-CI/publishing: our publishing stuff doesn't work on `dist: bionic` but generating spec PDF requires it

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#764]
some gory details at https://github.com/scala/scala-dev/issues/762

**Comment by dwijnand** [comment]
Move the `dist` to the `language spec (Jekyll)` job, leaving the other jobs (e.g. publishing) to use the default.  Now the default might've also changed since Dec 2020, but it might fix it for you.

**Comment by SethTisue** [comment]
do you know for sure whether you're allowed to set `dist:` at the job level and not the build level?

**Comment by dwijnand** [comment]
I'm fairly sure because this example seems to suggest it:

https://docs.travis-ci.com/user/multi-os/#example-multi-os-build-matrix

```yaml
jobs:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.2
```

seeing as you can define a matrix of not even linux, makes sense that the linux distribution is matrixable.
